### PR TITLE
Initial Dockerfile

### PR DESCRIPTION
**Pull request by matti**
Sample Dockerfile with everything enabled.

### CODE REVIEW

**Comment by mpolden** [comment]
Thanks, but I don't use Docker.

**Comment by pre** [comment]
@mpolden why would you release something as open source, and then not be open to ideas outside of your current comfort zone ? :)

**Comment by mpolden** [comment]
@pre I'm open to ideas, but as I said: I don't use Docker and the Dockerfile would likely end up unmaintained.

If people are interested in maintaining a Dockerfile somewhere else, I'd be willing to link to it from here.

**Comment by pre** [comment]
That is a pretty limited view on open source development. 

If you personally don't use it, what's there to maintain? If someone else finds it needing maintenance, there will be a PR (such as this). In either case, it is not supposed to be your personal problem. 

Should you embrace the "we" in open source, you will find Github much more rewarding than being limited to the "I" mindset. 

All the best :)

**Pull request closed without merging**
