### PR TITLE
Add dep and build goal

### PR DESCRIPTION
**Pull request by maximbaz**
[dep](https://github.com/golang/dep) is a very cool thing, it allows keeping dependencies local to the project without polluting `$GOPATH`. I generated `Gopkg.*` files with `dep init`. It makes sense to gitignore `vendor/` folder because thanks to `Gopkg.lock` it is easy to regenerate the folder with exactly the same versions of your dependencies.

Also added a `build` make-goal for convenience, to build the executable without putting it in `$GOPATH/bin`.

### CODE REVIEW

**Comment by mpolden** [comment]
Thanks, explicit dependencies is a good idea. However, I would like to wait until Go 1.11 and start using modules instead of `dep`.

**Comment by maximbaz** [comment]
Up to you

**Comment by maximbaz** [comment]
@mpolden Go 1.11 is out, you can start using modules now: https://arslan.io/2018/08/26/using-go-modules-with-vendor-support-on-travis-ci/

**Comment by mpolden** [comment]
Switched to modules in https://github.com/mpolden/echoip/commit/fefe3713699a0caf585d496a271e6f3a43c5188b. Thanks for the heads up, @maximbaz!

**Pull request closed without merging**
